### ISSUE TITLE
ability to auto join & stream in vc / stages? at launch

### ISSUE THREAD

**Issue by JoqniX** [dandln/TheEpicAudioStreamer#6]
hi i was wondering if it would be possible to add a feature to auto join voice channels and also a way to automatically move to speaker if in a stage? 

i usually use /joinst but it would be good if its possible to set it up to join automatically when the bot is online/ when launching via .bat 

idk much bout coding. but i wanted to ask. if i wanted to add more slash commands or edit the code stuff? i believe i should be looking in https://github.com/dandln/TheEpicAudioStreamer/blob/master/TEASLibrary/Bot.cs / Utils.cs  right?

p.s i wanted to say thank you for making such a really good tool to play music locally through discord bot~ i've been using it for months~ it helps alot~

**Comment by dandln** [comment]
Hey! I can definitely see the value in a feature like this, and it might tie in nicely with another change that I have been thinking about. Potentially boring technical detail below. :D

Essentially, to connect to a specific channel (would have to be passed to TEAS as a channel ID, as a channel name could be ambiguous), I need to enumerate each individual channel in a Guild (a Discord Server) to find the one that matches the given channel ID, and then connect to it. As it stands right now, the bot may technically be present in multiple Guilds at once. This means that, hypothetically speaking, a bot could be member of dozens of Guilds, with dozens of channels each, which would all have to be enumarted to find the matching voice channel to connect to, making this whole operation very inefficient.

Now, this form of multi-guild membership was never intended to be a feature of TEAS as it frankly doesn't make much sense and is also completely untested, so I have been thinking about requiring a Guild ID along with the bot token at startup so that the bot will only ever connect to one Guild at any time, which would also have the benefit that registration of Slash Commands would be much quicker. And finally, this would mean that only one Guild would have to be enumerated for the matching channel to connect to on startup.

I will look into this more soon, as well as into Stages in general as I never used/interacted with one before.

> idk much bout coding. but i wanted to ask. if i wanted to add more slash commands or edit the code stuff? i believe i should be looking in https://github.com/dandln/TheEpicAudioStreamer/blob/master/TEASLibrary/Bot.cs / Utils.cs right?

All the files host different aspects of the code so it depends on what you want to modifiy, but the Slash Commands are defined in the Bot class, yes.

**Comment by dandln** [comment]
Automatically joining and streaming to a voice channel is available now in [version 0.6.0](https://github.com/dandln/TheEpicAudioStreamer/releases/tag/v0.6.0)! I unfortunately don't have any way of testing this in Stages, but hopefully it should work the same way. I'm closing this issue for now, but please let me know if this is incompatible with Stages and I can see what I can do to work on this.

**Comment by JoqniX** [comment]
hewwo~ so i did test it in [TEAS v0.6.1](https://github.com/dandln/TheEpicAudioStreamer/releases/tag/v0.6.1)
it works well for vc channels~ 
sometimes if it doesnt output audio from virtual cable. i just had to make the bot rejoin the vc manually~ 

for stages
> so it does autojoin as a participant on stages. but i have to manually make it be a speaker! 
and yesh the bot is already a stage mod as well~


so if in case if you're adding a slash command feature to make it on stages~ it would be good if you could add slash options or args ( i forgot what the input thingy or the option thingy for the new slash commands api has~ ) 

the following are some ideas i had in mind .w. 

> for example - if you're making it as a new slash or updating a existing slash cmd like " /joinst " or " /start " 
1. either you can make the bot detect that the voice channel type is a stage channel , then under when the user triggers the slash command ( as a reply message, it could ask the user how they want the bot to stream by speaking on the stage? (without starting the stage) or speaking on the stage ( while starting the stage ) [ remember to add an option to notify others or not ]

cuz there maybe times some users dont want to notify @/everyone and they just wanna listen and vibe~ and for those who want it they can go with the notify one 
![Discord_YSHYxJBZ5V](https://user-images.githubusercontent.com/54277349/219967926-2e4d3e28-e38b-4ba5-97ac-f4f530ffe450.png)

2. idk how 1st example would work cuz of 0.6.1's auto join feature. so ig this might be the better one~
an new arg for config file? and additonal options for /joinst or /start
something like this ( this is an example of slash options and inputs from slashbot
![image](https://user-images.githubusercontent.com/54277349/219968083-d43ec94c-eb23-4104-8b81-c0aa3feaebde.png)

so here how we could make it work for TEAS would be like
options : 
Speak on Stage -> yes | no
Notify Others? -> ( why not make this as a option type? so my default it would not notify ( meaning start the stage and mention @ everyone ) but if users want it they can select this arg so it speaks on stage and notifys others~ )

dunno if my ideas could work or not~ and also i havent checked if its possible to not notify when starting the stage? ig it might be available in discord api or in c/ c# libaries? 

but yea tldr its just the automatic setup~ 
if ppl wanted to do this manually everytime they use this they can~ 
for me i usually run teas via bat on startup~ and manually did this ever since. but if this automatic setup for stage works then it would help alot .w.

**Comment by dandln** [comment]
Thanks for the detailed ideas and explanation! I'm glad that the bot at least manages to connect to the stage 😅 To be honest, since I have basically no ability to test the bot's interaction with stages, I can't see myself developing features in that direction at the moment. The bot is not really meant to interact much with a server apart from joining/speaking in a voice channel, so things like actively starting stages/notiying users do feel a little out of scope for it, and I want to avoid feature creep here by going down that route.

**Comment by JoqniX** [comment]
yea i totally understand~ so its fine~ i feel like its better how it is now~ thanks for letting me know your thoughts on this as well .w.
