### ISSUE TITLE
Bot token validation error + some doubts 

### ISSUE THREAD

**Issue by JoqniX** [dandln/TheEpicAudioStreamer#9]
hewwo~ thank you dandln for updating this wonderful app! 

so i was trying to test out the new version but im faced with a few errors idk what im doing wrong?
and yesh in these images i was trying out the old way of mentioning the bottoken cuz i had trouble getting configfile to work!

![image](https://user-images.githubusercontent.com/54277349/219904854-e6d3e30d-e179-47dd-8ca7-0f2e5fc0f154.png)
![image](https://user-images.githubusercontent.com/54277349/219904874-d1322251-7ccf-49ed-a068-f961a852185b.png)

so yea there's a few doubts i had as well~ so the new readme said to use a config file! instead of the using bottoken like on v0.5.2
so i did this in the config file ( yesh ill blur out the bottoken etc just in case .w.)
![NRctxgVY6E](https://user-images.githubusercontent.com/54277349/219904927-4421b41c-b122-4689-9a66-82979effa332.png)

but this doesnt work for some reason? 

hope its okie to ask some doubts i had >///<
bout --admin roles!
> i believe i should be just pasting the role id? right? without the usual <@&RoleID> ( i believe i shouldnt be typing down the role name? )

about -c or --channel
> ill let you know bout in https://github.com/dandln/TheEpicAudioStreamer/issues/6 after getting it to work and testing for stages .w.

about botconfig
> the readme mentioned to use it as [configfile] but it doesnt read it tho? 
if it was a argument then it would have been more easier ig? idk ( yes it was in the same folder as the exe) 
![WindowsTerminal_29mzSmhv6J](https://user-images.githubusercontent.com/54277349/219905252-849a7766-2631-48e0-b94f-1160cf569c0a.png)
![explorer_UlQALlwd7N](https://user-images.githubusercontent.com/54277349/219905263-393bf7ab-5a06-4c0e-8fcf-b213ee3cf659.png)

**Comment by JoqniX** [comment]
oh yea i forgot to mention. as v060 is saying "invaild bot token" when following along the interactive assistant
![image](https://user-images.githubusercontent.com/54277349/219905429-66007961-65d3-4042-a7c0-fc371dd22699.png)

the same bot token does work perfectly on v0520

**Comment by dandln** [comment]
Hey! Of course it's okay to ask about these things, that's what this feature is there for. :) Okay so let's unpack this one by one:
* The `-t` parameter no longer accepts a filepath like in previous versions, only the actual bot token, which is why your attempts to run TEAS in your first screenshot fail. I should probably make this more clear in the Readme to be fair.
* The new `botconfig.txt` file has a different format than just chaining the CLI arguments, which is why TEASConsole can't parse the file in your second screenshot. A config file looks like this:
  ```
  GuildID=
  BotToken=
  DefaultDevice=
  DefaultChannel=
  AdminUsers=
  AdminRoles=
  ```
* Admin roles can just be passed by its name, no ID needed. So if your admin role is called "Botusers" for example, you can just pass this name to the bot.
* The `[configfile]` part of the usage instructions is just a placeholder for the path to your configuration file. So for example, if you would want to use a file at `configuration.txt`, your command to run TEASConsole should be
`TEASConsole_v060.exe "configuration.txt"`. If no config file is found at this location, the assistant will help you create a new one there. The default is `botconfig.txt`.
* And finally to your last point, this seems to be an issue with the validation that I'm running for the bot token, which seem to have changed in length recently. This theoretically shouldn't happen if you used the same token as in v0.5.2, but any newly generated ones will likely fail validation. I'll get a hotfix for this out asap.

**Comment by dandln** [comment]
[Hotfix now out](https://github.com/dandln/TheEpicAudioStreamer/releases/tag/v0.6.1) - Can you check whether this resolves your issue with the configuration assistant please?

**Comment by JoqniX** [comment]
Yesh it finally works thank you for explaining how to make it work~ 
so yea i was able to get the bottoken working + the admin roles as well .w.
thanks again! 💖

**Comment by JoqniX** [comment]
if possible could you help me with this as well? 
 idk what im doing wrong but i cant make TEAS launch as .bat now~
my older way was like this 
```@ECHO OFF
start "" /d "E:\TEAS\" "TEASConsole_v0520.exe" -t "E:\TEAS\onxaiatoken.txt" -d "VB-Audio VoiceMeeter VAIO"```

when launching the bat file it just opens teas cli and closes?
how do i do this for v0.6.1?

**Comment by dandln** [comment]
See in my comment above :)

> * The `-t` parameter no longer accepts a filepath like in previous versions, only the actual bot token, which is why your attempts to run TEAS in your first screenshot fail.

and

> * The `[configfile]` part of the usage instructions is just a placeholder for the path to your configuration file. So for example, if you would want to use a file at `configuration.txt`, your command to run TEASConsole should be
`TEASConsole_v060.exe "configuration.txt"`. If no config file is found at this location, the assistant will help you create a new one there. The default is `botconfig.txt`.

There will be no need to specify `-d` or `-t` anymore if your config file is set up correctly.

**Comment by JoqniX** [comment]
sorry i was inactive for a while~ 
but yea i was able to get it working~ 

i made a few changes to the bat command -
``@ECHO OFF
start "" E:\TEAS\TEASConsole_v061.exe`` 
this worked.  thanks again~

**Comment by JoqniX** [comment]
im having the issue where TEAS doesnt read the botconfig.txt on its own folder? for some reason? when adding to startup as a shortcut! 
![image](https://github.com/dandln/TheEpicAudioStreamer/assets/54277349/a04ab06c-2e17-47dd-93be-237c1e98e62a)

but when i manually open TEAS again it works~ sometimes~ 
does TEAS save the config in any other places such as appdata/temp etc?

**Comment by dandln** [comment]
Only reason that I can see how this could happen is if you haven't put the correct folder into the "Start in:" field of the shortcut settings, because that's where it will look for the file I assume. Make sure that's the same folder where the config file is in.

**Comment by JoqniX** [comment]
ah i totally forgot bout getting back to this~ so yea i was able to get it working. it was just like yu said. after messing around a bit it finally works~ but yea it was kinda weird when this issue occured i had put like the bot token etc details~ i wonder where those configs went? since it kept on asking to enter details as it failed to locate the config. but yeea anyways its working now, that's what it matters~ 

thank you! 💖
